name: CI

on:
  workflow_call:
  push:
    branches:
    - '*'
    tags:
    - 'v*'
  pull_request:
    branches:
    - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - run: make test
